/*

Legacy state providing Cells API (interface)

Provides two base object prototypes (classes): CellGrid and Cell
It's a fake DetailState, can not be cloned properly (because it references
global objects).

It partially implements other interfaces like HeightMap, States etc
these props will be reachable via Cell object.
*/

export const protoCell = {

  id: undefined, // cell identifier, must be defined
  get height() { return pack.cells.h[this.id] },
  get biome() { return pack.cells.biome[this.id] },
  get burg() { return pack.cells.burg[this.id] },

}

export const CellGrid = {

    protoCell: protoCell, // prototype for all Cell objects generated by the Grid
    cells: pack.cells, // <-- !!! global ref


}
